version = 3.8.0
runner.dialect: scala213source3
project.git: true

maxColumn: 120
align.preset: none

danglingParentheses {
  callSite: false
  ctrlSite: false
  defnSite: false
  preset: false
}

rewrite {
  rules: [
    Imports,
    PreferCurlyFors,
    RedundantBraces,
    RedundantParens,
    SortModifiers
  ]
  redundantBraces {
    ifElseExpressions: true
    stringInterpolation: true
  }
  imports {
    sort: scalastyle
  }
}
