addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.6")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.8.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.6.1")
addSbtPlugin("io.h8.sbt" %% "sbt-dependencies" % "1.0.7")
addSbtPlugin("io.h8.sbt" % "sbt-scoverage-summary" % "1.0.6")
addSbtPlugin("io.h8.sbt" % "sbt-testkit" % "2.0.2")
