name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    secrets: inherit
    uses: h8io/gha/.github/workflows/test.yaml@v3
    with:
      timeout-minutes: 5